// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-v6rH-ORKnB_cbzlzqY72vsDzdBJzqhE',
    appId: '1:500878566916:web:37b34b760e0236b0bab751',
    messagingSenderId: '500878566916',
    projectId: 'smart-card-system-f1da1',
    authDomain: 'smart-card-system-f1da1.firebaseapp.com',
    storageBucket: 'smart-card-system-f1da1.firebasestorage.app',
    measurementId: 'G-9QJBCTFP59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOyoy73PNpub86fALIhdgqgl8KoRHI8kI',
    appId: '1:500878566916:android:b8dc340a6dc3ff44bab751',
    messagingSenderId: '500878566916',
    projectId: 'smart-card-system-f1da1',
    storageBucket: 'smart-card-system-f1da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjMjEyYv4s7Dk4phZ6XRg7-RrcdBaXB4',
    appId: '1:500878566916:ios:73ed427d7501b48fbab751',
    messagingSenderId: '500878566916',
    projectId: 'smart-card-system-f1da1',
    storageBucket: 'smart-card-system-f1da1.firebasestorage.app',
    iosBundleId: 'com.example.smartCardAppPassenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgjMjEyYv4s7Dk4phZ6XRg7-RrcdBaXB4',
    appId: '1:500878566916:ios:73ed427d7501b48fbab751',
    messagingSenderId: '500878566916',
    projectId: 'smart-card-system-f1da1',
    storageBucket: 'smart-card-system-f1da1.firebasestorage.app',
    iosBundleId: 'com.example.smartCardAppPassenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-v6rH-ORKnB_cbzlzqY72vsDzdBJzqhE',
    appId: '1:500878566916:web:c777a210a82326d3bab751',
    messagingSenderId: '500878566916',
    projectId: 'smart-card-system-f1da1',
    authDomain: 'smart-card-system-f1da1.firebaseapp.com',
    storageBucket: 'smart-card-system-f1da1.firebasestorage.app',
    measurementId: 'G-42GJ94QF6Q',
  );
}
